### ISSUE TITLE
youtube-dl won't update

### ISSUE THREAD

**Issue by ipkpjersi** [firedm/FireDM#242]
Hi,

According to `python3`, I am on the latest youtube-dl (April 26):
 ![](https://i.imgur.com/dzgJLSj.png)
 
However, in FireDM, it says I am on an older youtube-dl (April 7):
![](https://i.imgur.com/bn71BvJ.png)

Also, when I check for updates, it says firedm is up to date:
![](https://i.imgur.com/WzRaXmT.png)

Because of that, FireDM continuously loops checking for downloads for youtube videos, and never lets me actually download the video:
![](https://i.imgur.com/2mK4yLR.png)

**Comment by firedm** [comment]
@ipkpjersi 
if you running from APPIMAGE version, unfortunately you can't update youtube-dl, this is due to the nature and limitation of this format
the only way is to wait until new version get releases, or if you want the latest up-to-date version, you can run from the source, 
follow steps in readme file to know how https://github.com/firedm/FireDM#running-from-source-code-inside-virtual-environment
and you can update youtube-dl any time
