### ISSUE TITLE
Could anyone tell information about " use threadpoolexecuter instead of individual threads" and " Use download Simulator"

### ISSUE THREAD

**Issue by mohitmeanslove** [firedm/FireDM#245]
I am not able to understand these two things. 
Please give information about this.

**Comment by firedm** [comment]
@mohitmeanslove 
"download Simulator" option is used for debugging, and from its name it doesn't download data from remote server or write anything on hard disk, it only does fake downloading, this is useful if a developer wants to test user interface [GUI] without downloading data from internet.

" use threadpoolexecuter instead of individual threads", this is how you make multi-threading / multi-connection in python in python, and mostly there is no big difference between the 2 methods 

these 2 options are under debugging section for developers, normal user can just ignore it, and it might be removed in future releases

**Comment by mohitmeanslove** [comment]
Thanks a lot
