### ISSUE TITLE
Website authentication not sticking after a re-launch

### ISSUE THREAD

**Issue by christubuntu** [firedm/FireDM#282]
typing my Youtube username and password in that field, and restarting Firedm, all the credentials are gone. Also, irc, the last time I was able to download videos in the "watch later" playlist. Now I can't as the app can't find anything. Are these 2 issues related?
![8iA1yzmBQn](https://user-images.githubusercontent.com/55885756/134469213-1050229b-85e4-4f11-870f-a9b4247de6e3.png)
d?

**Comment by firedm** [comment]
@christubuntu 
FireDM store settings on disk in a plain text, that's why (as a security precaution) it avoids storing your credentials 
however we can give this to the user to decide in the future and add another option to store credentials with a proper warning message

> the last time I was able to download videos in the "watch later" playlist. Now I can't as the app can't find anything. 

try to switch to yt-dlp from settings>Video options   and try again.
and if the video you trying to download needs a login credentials, you should type it

**Comment by firedm** [comment]
done in latest release

![image](https://user-images.githubusercontent.com/58998813/135017193-ce4a98d9-7d97-431c-8b8b-8e7299abcf31.png)
