### ISSUE TITLE
Update failed!!!! ... try again

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#302]
Hi,

I tried to update the application but that's the result:

![image](https://user-images.githubusercontent.com/69006279/138195007-649f48ff-6fe4-454b-8721-29368313e332.png)

Any idea?
In the logs, I cannot see anything about this error.

Question: will the update reset my download list?

Thanks
Daniele

**Comment by firedm** [comment]
@jdaniele71 

> It seems It has no rights to write files under C:\Program Files (x86)\FireDM

this is correct, 
the fix for this is to copy firedm folder in another location which doesn't need admin rights, and you can update without a problem, or better download new version manually, extract the folder and move it to a proper place with write permission

maybe in the future will add feature to prompt for admin permission, to solve this problem

> So maybe I should try the normal installer...

it is not a good idea, since installing dependencies manually on windows is a headache specially "pycurl"



![img](https://user-images.githubusercontent.com/69006279/138379541-9e0c00f2-eae9-4b06-9710-90a694341410.png)
great, your settings folder is stored globally, it will be re-used without a problem
