### ISSUE TITLE
How has cx_freeze worked out for you?

### ISSUE THREAD

**Issue by PySimpleGUI** [firedm/FireDM#329]
Hi!

I saw in your release notes that you use cx_freeze.  

I'm getting close to releasing a GUI front-end for pyinstaller and am wondering if cx_freeze works better in some situations.  I think that supporting both is the direction I'm headed.

![image](https://user-images.githubusercontent.com/46163555/140392378-393f9786-1b78-4dd2-9122-70663a833311.png)

Unlike the previous EXE Maker GUI, this one has all of the options available:

![image](https://user-images.githubusercontent.com/46163555/140392919-c2a7089f-652f-46f5-8690-a7a704fcced0.png)

🔥🔥 Great to see FireDM is still on fire!  🔥🔥

**Comment by firedm** [comment]
Hello Mike,
Your EXE maker looks great,

I tried both pyinstaller and cx_freeze, and found cx_freeze more superior in performance, 
this evaluation based on my trial 2 years ago, not sure if things has got better with new pyinstaller releases
my concern regarding pyinstaller is its need to extract contents to a temp folder, which gives a startup delay penalty, also need to be careful with paths


here is a [link](https://github.com/firedm/FireDM/blob/master/scripts/exe_build/exe-fullbuild.py) for my exe build script, it has some extra code since it build 2 exe files and do some post processing


> 🔥🔥 Great to see FireDM is still on fire!  🔥🔥

Thanks  :)
