### ISSUE TITLE
Frozend downloads at 99% marked as active

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#336]
Hi,

even if the downloads are frozen at 99% with 0 Kb/s speed, they are still marked as "active" and "downloading", blocking the start of all other downloads.

![image](https://user-images.githubusercontent.com/69006279/140458907-d9849ef3-72ce-4ef1-a877-20c52df12d20.png)

Thanks
Daniele

**Comment by firedm** [comment]
this is really a bad problem, should find why we have segment merge error in first place, and yes it is still active since it keep trying in background
the problem i can't reproduce same problem in my machine, which make it very difficult to fix

one off-topic question, are you running 2 instances of firedm application in same time?

**Comment by l3xrom** [comment]
@firedm
I recently faced the same problem, more than half of the playlist froze at 99%, and some videos were downloaded, but I manually stopped the frozen downloads to start downloading the next ones.
In my case, it turned out that this happened due to the choice of dash video in which the audio stream that was selected automatically had a weight of 0kb or a little more, that is, it was incorrect on the server. I had to manually select the audio stream for each such video and after that everything was downloaded.

![gif](https://s1.hostingkartinok.com/uploads/images/2021/11/ac35ef9759e45d9f0012766229c646b2.gif)

Examples of such videos in this playlist
[https://www.youtube.com/playlist?list=PL7ud2MDfWE_mReWkpem543EDUx9XZcumQ](url)

**Comment by jdaniele71** [comment]
@firedm 
>this is really a bad problem, should find why we have segment merge error in first place, and yes it is still active since it keep trying in background
the problem i can't reproduce same problem in my machine, which make it very difficult to fix

Yeah, I have to move my ass, add the logs and/or start a debug session in VS Code and see what happens because this issue is very frequent on my rig.
I have Anaconda, so "conda" to manage the packages and environments. (no standard Python installation).
Do you think will I be able to run the app from source code?

> one off-topic question, are you running 2 instances of firedm application in same time?

Never...

PS: may I have a little place at the bottom of the file contributors.md? 😋

@l3xrom 
I've just did regular downloads.

Thanks
Daniele

**Comment by firedm** [comment]
@l3xrom 
This is really helpful, thanks for the link and your debugging, great work :+1:

**Comment by firedm** [comment]
@jdaniele71 
you can run from source code on windows, and if you have a problem installing pycurl, you can download binaries from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl) , choose a proper binary file that match your python version
this will be easier for testing and you can test latest features

sure your input to this project is valuable, and you are one of the good contributors, will update the list soon

**Comment by jdaniele71** [comment]
> @jdaniele71 you can run from source code on windows, and if you have a problem installing pycurl, you can download binaries from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl) , choose a proper binary file that match your python version this will be easier for testing and you can test latest features

Perfect, I will try it, thanks.
 
> sure your input to this project is valuable, and you are one of the good contributors, will update the list soon

Thanks a lot @firedm !
I'm honored! 🙏

**Comment by firedm** [comment]
fixed, the problem in commit https://github.com/firedm/FireDM/commit/637e053e0cb3477140f7ce7c133b01a495ee0260

**Comment by jdaniele71** [comment]
> fixed, the problem in commit [637e053](https://github.com/firedm/FireDM/commit/637e053e0cb3477140f7ce7c133b01a495ee0260)

Great @firedm !!!
Thanks
