### ISSUE TITLE
Custom FFmpeg

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#359]
Hello, in the release info of FireDM, it says " ffmpeg.exe included, you can download latest version here".

I read in the in the github page of  yt-dlp :

"Note: There are some regressions in newer ffmpeg versions that causes various issues when used alongside yt-dlp. Since ffmpeg is such an important dependancy, we provide custom builds with patches for these issues at yt-dlp/FFmpeg-Builds. See the readme for details on the specifc issues solved by these builds"

https://github.com/yt-dlp/FFmpeg-Builds

So, FireDM uses the classic FFmpeg or custom FFmpeg made by yt-dlp ?

**Comment by firedm** [comment]
@trimechee 
thanks for reporting this
FireDM uses classic ffmpeg, 

some videos has encoding bugs which cause ffmpeg to fail while processing, as a workaround FireDM uses muxing command without "-c copy" flag as a fallback in case it failed but with the cost of processing time, since it will take several minutes to do the job compared to few seconds in normal situation

i tested these builds and i confirm it works without a problem, and it will be included in FireDM instead of classic ffmpeg

thanks again for sharing

**Comment by trimechee** [comment]
Ohh awesome !! Thank you very much for this clarification and for including this new FFmpeg!

but I have a fear, I see on the relaeses pages of this customized FFmpeg: "Auto-Build 2021-11-16 12:48 Latest

Drop nonfree builds

We do not have the rights to re-distribute them "

so ordinary users are not allowed to use these modified FFmpegs? is it prohibited by the law ?

**Comment by firedm** [comment]
> Drop nonfree builds
> 
> We do not have the rights to re-distribute them "
> 
> so ordinary users are not allowed to use these modified FFmpegs? is it prohibited by the law ?

I am not expert in license and legal issue
but i think they mean they didn't include a non free builds because they don't have the right to distribute them

plus FireDM is open source and doesn't use any code from ffmpeg source

maybe if someone is expert in this could enlighten us

**Comment by trimechee** [comment]
Ahh that's reassuring ! thank you very much for these clarifications ! I also hope that someone can inform us a little more about these legal matters @yt-dlp
