### ISSUE TITLE
Cli mode not working at all.

### ISSUE THREAD

**Issue by sajjadhossanshimanto** [firedm/FireDM#386]
I think there's more to do with the cliview.
1. Interactive mode exits instade of starting download.
![IMG_20211203_200329](https://user-images.githubusercontent.com/39458868/144615658-6e5a524a-2d61-4556-a742-39325041b1a2.jpg)
2. Batch download exits just after starting download
![IMG_20211203_200255](https://user-images.githubusercontent.com/39458868/144615873-c1dfd37b-f772-4dab-837f-4ceb854c2d5d.jpg)

**Comment by firedm** [comment]
@sajjadhossanshimanto 
thanks for reporting this
will look into this and try to fix it

**Comment by jcmag** [comment]
Is this issue really fixed? Because I can't download youtube videos using the command line:

C:\Users\jcmag\Downloads\FireDM_2021.12.2.post1\FireDM>firedm.exe --version
FireDM version: 2021.12.2.post1


C:\Users\jcmag\Downloads\FireDM_2021.12.2.post1\FireDM>firedm.exe -o C:\Users\jcmag\test https://www.youtube.com/watch?v=JXtfKMH6X44

>> Downloading the following url(s):
https://www.youtube.com/watch?v=JXtfKMH6X44
>> [youtube] JXtfKMH6X44: Downloading webpage
>> [youtube] JXtfKMH6X44: Downloading android player API JSON
>>

>> --------------------------------------------------
>> start downloading file: "Omicron _the symbol_ in Mathematics  - Numberphile.mp4", size: 221.08 MB, to: C:\Users\jcmag\test
>> url: "https://www.youtube.com/watch?v=JXtfKMH6X44"

 5.1% [=                   ] 11.3MB/221.1MB
C:\Users\jcmag\Downloads\FireDM_2021.12.2.post1\FireDM

And the download never finishes...

**Comment by Aboghazala** [comment]
> Is this issue really fixed? Because I can't download youtube videos using the command line:

@jcmag

this fix already done in current master branch and will be available in coming release "very soon"
