### ISSUE TITLE
Benchmark methodology

### ISSUE THREAD

**Issue by codl** [firedm/FireDM#397]
Hi, I have issues with the methodology in the benchmark vs aria2 linked in the readme, embedded below as a video for easy seeking:

https://user-images.githubusercontent.com/315139/146031412-c52aa5ab-2d90-471f-bb01-2ee4d3c2813c.mp4

The benchmark invokes aria2 with the command `aria2c -x8 -k1M --dir="d:\test\aria" --file-allocation=none $URL`.

I believe the intention of `-x8 -k1M` was to match the 8 connections used by FireDM, however it does not achieve that, and aria2 reports throughout the benchmark that it is using the default 5 connections: `CN:5`. In this situation, it is not surprising that aria2 "loses" to FireDM, in fact aria2 with 5 connections loses to itself with 8 connections, if both are run at the same time. If they're run separately, then results are virtually identical.

A more complete aria2c command line would use `--max-concurrent-downloads=8 --max-connection-per-server=8 --split=8`, or `-j 8 -x 8 -s 8` for short. I couldn't reproduce the benchmark myself with a fixed command line, since FireDM doesn't seem to support downloading arbitrary URLs anymore.

Regardless, what is the purpose of this benchmark? By running both tools at the same time on what is ostensibly a limited downlink, the only thing it is showing is which tool is better at fighting for limited bandwidth. Was this the intention? To show that FireDM thrives in an environment where other download managers are running on the same computer? On the same connection?

**Comment by Aboghazala** [comment]
@codl 
thanks to bring this old topic up
i think this test has been done during the early stages of this project, to see if it can stand against good download managers like Aria2 in this case
i believe we should remove this test  reference from readme file, since this project is made to benefit people and it has no intention to compete with any other Download managers, or seeking to be commercialized or collect donations.

thanks again for this note
